---
- hosts: 127.0.0.1
  connection: local 
  tasks:
  - quantum_network:
        auth_url={{ endpoint }} 
        login_username={{ admin_user }}
        tenant_name={{ tenant_name }}
        login_tenant_name={{ tenant_name }}
        login_password={{ admin_password }}
        name={{ name }}
        {% if delete %}
        state=absent
        {% else %}
        state=present
        {% endif %}
        shared=true
  {% if not delete %}
  - quantum_subnet:
        auth_url={{ endpoint }} 
        login_username={{ admin_user }}
        tenant_name={{ tenant_name }}
        login_tenant_name={{ tenant_name }}
        login_password={{ admin_password }}
        name={{ subnet_name }} 
        network_name={{ name }} 
        {% if delete %}
        state=absent
        {% else %}
        state=present 
        no_gateway=true 
        dns_nameservers=8.8.8.8
        cidr={{ cidr }}
        {% endif %}
  {% endif %}
