---
- hosts: localhost

  vars:
    dockerfiles:
    {% for dockerfile in dockerfiles %}
      - docker_image_name: {{ dockerfile.docker_image_name }}
        dockerfile_fn: {{ dockerfile.dockerfile_fn }}
    {% endfor %}

  tasks:
    {% for dockerfile in dockerfiles %}
    - name: build_docker_{{ dockerfile.docker_image_name }}
      shell: chdir={{ build_dir }} docker build -f {{ dockerfile.dockerfile_fn }} --rm -t {{ dockerfile.docker_image_name }} .
    {% endfor %}

    - name: run docker-compose
      shell: docker-compose -p {{ docker_project_name }} -f /opt/xos/synchronizers/onboarding/docker-compose/docker-compose.yml up -d

