xos_db:
    image: xosproject/xos-postgres
    expose:
        - "5432"

xos_synchronizer_openstack:
    command: bash -c "sleep 120; python /opt/xos/synchronizers/openstack/xos-synchronizer.py"
    image: xosproject/xos-synchronizer-openstack
    labels:
        org.xosproject.kind: synchronizer
        org.xosproject.target: openstack
    links:
        - xos_db
    volumes:
        - .:/root/setup:ro
        - ../vtn/files/xos_vtn_config:/opt/xos/xos_configuration/xos_vtn_config:ro

xos_synchronizer_onos:
    image: xosproject/xos-synchronizer-openstack
    command: bash -c "python /opt/xos/synchronizers/onos/onos-synchronizer.py -C /opt/xos/synchronizers/onos/onos_synchronizer_config"
    labels:
        org.xosproject.kind: synchronizer
        org.xosproject.target: onos
    links:
        - xos_db
    volumes:
        - .:/root/setup:ro
        - ./id_rsa:/opt/xos/synchronizers/onos/onos_key:ro  # private key

# FUTURE
#xos_swarm_synchronizer:
#    image: xosproject/xos-swarm-synchronizer
#    labels:
#        org.xosproject.kind: synchronizer
#        org.xosproject.target: swarm

xos:
    command: python /opt/xos/manage.py runserver 0.0.0.0:80 --insecure --makemigrations
    image: xosproject/xos
    links:
        - xos_db
    ports:
        - "80:80"
    volumes:
        - .:/root/setup:ro
        - ../vtn/files/xos_vtn_config:/opt/xos/xos_configuration/xos_vtn_config:ro
        - ./id_rsa.pub:/opt/xos/synchronizers/onos/onos_key.pub:ro
