xos_db:
    image: xosproject/xos-postgress
    expose:
        - "5432"

xos_synchronizer_openstack:
    image: xosproject/xos-synchronizer-openstack
    labels:
        org.xosproject.kind: synchronizer
        org.xosproject.target: openstack

# FUTURE
#xos_swarm_synchronizer:
#    image: xosproject/xos-swarm-synchronizer
#    labels:
#        org.xosproject.kind: synchronizer
#        org.xosproject.target: swarm

xos:
    image: xosproject/xos
    ports:
        - "8000:8000"
    links:
        - xos_db
