---
- hosts: {{ instance_name }}
  gather_facts: False
  connection: ssh
  user: ubuntu
  sudo: yes
  tasks:
  - name: install openvpn
    apt: name=openvpn state=present update_cache=yes

  - name: write key
    shell:
       |
       printf "{{ server_key }}"  > "/opt/xos/observers/vpn/static.key"

  - name: write config
    shell: printf "dev tun\nifconfig 10.8.0.1 10.8.0.2\nsecret /opt/xos/observers/vpn/static.key\nkeepalive 10 60\nping-timer-rem\npersist-tun\npersist-key" > "/opt/xos/observers/vpn/server.conf"

  - name: start openvpn
    shell: openvpn /opt/xos/observers/vpn/server.conf
