---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - os_network:
      name: {{ name }}
      project: {{ project_name }}
      shared: true
      {% if not delete -%}
      state: present 
      {% else -%}
      state: absent
      {% endif -%}
      auth:
        auth_url: {{ endpoint }}
        username: {{ admin_user }}
        password: {{ admin_password }}
        project_name: {{ project_name }}

{% if not delete -%}
  - os_subnet:
       name: {{ subnet_name }}
       network_name: {{ name }}
       {% if not delete -%}
       state: present
       dns_nameservers: 8.8.8.8
       cidr: {{ cidr }}
       {% if use_vtn -%}
       gateway_ip: {{ gateway }}
       {% endif -%}
       {% else -%}
       state: absent
       {% endif -%}
       auth:
         auth_url: {{ endpoint }}
         username: {{ admin_user }}
         password: {{ admin_password }}
         project_name: {{ project_name }}
{% endif -%}

