---
- hosts: cmi
  connection: ssh
  user: root
  vars:
    eth_device: eth0
    cmi_password: XOScdn123$
    cmi_hostname: xos-cloudlab-cmi-vtn.opencloud.us
    cmi_dns: 8.8.8.8
    cdn_site: CoBlitz Test
    cdn_short_name: cobtest
    cdn_name: CoBlitz
    gateway_ip: 10.124.0.1
    gateway_mac: 00:8c:fa:5b:09:d8
    node_hostname: xos-cloudlab-cmi-vtn.opencloud.us
  tasks:
  - name: fix the networking
    shell: "{{ item }}"
    with_items:
      - ip route del default || true
      - ip route add default via {{ gateway_ip }}
      - arp -s {{ gateway_ip }} {{ gateway_mac }}

  - name: copy over setup answers
    template: src=templates/setup_answers.txt dest=/root/setup_answers.txt

  - name: run the setup script
    shell: /a/sbin/setup.sh < /root/setup_answers.txt

  - name: fix onevapi CDNPrefix bug
    shell: sed -i 's/hostname/str/g' /vservers/coplc/usr/share/cob_api/COB/PublicObjects/CDNPrefix.py

  - name: fix onevapi OriginServer bug
    shell: sed -i 's/attrToCheck = "edge_hosttype"/attrToCheck = "edge_hosttype_broken"/g' /usr/share/cob_api/COB/PublicObjects/OriginServer.py

  - name: copy over cmi setup template
    template: src=templates/setup_cmi.sh dest=/vservers/coplc/root/setup_cmi.sh

  - name: copy over cmi node setup template
    template: src=templates/setup_cmi_node.sh dest=/vservers/coplc/root/setup_cdmi_node.sh
