tosca_definitions_version: tosca_simple_yaml_1_0

description: Some basic fixtures

imports:
   - custom_types/xos.yaml

topology_template:
  node_templates:
    MyDeployment:
      type: tosca.nodes.Deployment

    mysite:
      type: tosca.nodes.Site
      properties:
          display_name: MySite
      requirements:
          - deployment:
               node: MyDeployment
               relationship: tosca.relationships.SiteDeployment
               requirements:
                   - controller:
                       node: newcontroller
                       relationship: tosca.relationships.UsesController

    padmin@vicci.org:
      type: tosca.nodes.User
      properties:
          password: letmein
#          encrypted_password: pbkdf2_sha256$12000$Qufx9iqtaYma$xs0YurPOcj9qYQna/Qrb3K+im9Yr2XEVr0J4Kqek7AE=
          firstname: XOS
          lastname: admin
          is_admin: true
      requirements:
          - site:
              node: mysite
              relationship: tosca.relationships.MemberOfSite





foo

