tosca_definitions_version: tosca_simple_yaml_1_0

description: Some basic fixtures

imports:
   - custom_types/xos.yaml

topology_template:
  node_templates:
    MyDeployment:
      type: tosca.nodes.Deployment
      properties:
          flavors: m1.large, m1.medium, m1.small

    mysite:
      type: tosca.nodes.Site
      properties:
          display_name: MySite
      requirements:
          - deployment:
               node: MyDeployment
               relationship: tosca.relationships.SiteDeployment

    # Include the Tenant view so we can make it a default of padmin@vicci.org
    Tenant:
      type: tosca.nodes.DashboardView
      properties:
          no-create: true
          no-update: true
          no-delete: true

    padmin@vicci.org:
      type: tosca.nodes.User
      properties:
          password: letmein
#          encrypted_password: pbkdf2_sha256$12000$Qufx9iqtaYma$xs0YurPOcj9qYQna/Qrb3K+im9Yr2XEVr0J4Kqek7AE=
          firstname: XOS
          lastname: admin
          is_admin: true
      requirements:
          - site:
              node: mysite
              relationship: tosca.relationships.MemberOfSite
          - tenant_dashboard:
              node: Tenant
              relationship: tosca.relationships.UsesDashboard

