---
# exampletenant_playbook

- hosts: "{{ instance_name }}"
  connection: ssh
  user: ubuntu
  sudo: yes
  gather_facts: no

  tasks:
  - name: install apache
    apt:
      name=apache2
      update_cache=yes

  - name: write message
    shell: echo "{{ tenant_message }}" > /var/www/html/index.html

